/* ==========================================================================
   IRS Protect Plus — site configuration
   This is the only file you need to edit to connect the site to your
   business. Every value is optional; the site degrades gracefully when a
   value is blank (forms fall back to email, contact rows hide, etc.).
   ========================================================================== */
window.SITE_CONFIG = {

  /* Company details shown on the Contact page, in the legal pages and in
     email fallbacks. Leave a value blank to hide that row. */
  company: {
    name: 'Best Vision Accounting',
    legalName: 'Best Vision Accounting, LLC',
    url: 'https://bvaccounting.com',
    email: 'info@bvaccounting.com',   // also the email fallback for forms
    phone: '(305) 220-9616',
    fax: '(305) 220-9617',
    hours: 'Lun–Vie: 9am–5pm · Sáb–Dom: cerrado',
    hoursEn: 'Mon–Fri: 9am–5pm · Sat–Sun: closed',
    /* Opening hours for search engines: days (Mo Tu We Th Fr Sa Su) and 24h times. */
    openingHours: [{ days: ['Mo', 'Tu', 'We', 'Th', 'Fr'], opens: '09:00', closes: '17:00' }],
    /* Official social profiles (used by search engines to connect the brand). */
    social: [
      'https://www.facebook.com/BVAccountingMiami',
      'https://www.instagram.com/bestvisionaccounting'
    ],
    address: '11401 SW 40th St, Suite 265, Miami, FL 33165',
    /* The same address split into parts, for search engines (structured
       data). Keep it identical to the address above and to the Google
       Business Profile. After editing, run the build (see README). */
    streetAddress: '11401 SW 40th St, Suite 265',
    city: 'Miami',
    region: 'FL',
    postalCode: '33165'
  },

  /* The single membership offered. Shown in the enrollment summary. */
  plan: { name: 'IRS Protect Plus', price: 19.99 },

  /* Hosted checkout link. A Stripe Payment Link works out of the box (the
     member's email and a reference ID are appended). When set, enrollment
     sends the member here after they confirm; when blank, the enrollment is
     delivered like any other form and your team completes it manually. */
  checkoutUrl: '',    // e.g. 'https://buy.stripe.com/xxxxxxxx'

  /* Form delivery. Any endpoint that accepts a multipart/form-data POST
     works: Formspree, Basin, Getform, Netlify Forms or your own API.
     Notice uploads are sent as `attachments`. If blank, forms fall back to
     opening the visitor's email app addressed to company.email. If that is
     blank too, the visitor is asked to contact you directly. */
  forms: {
    endpoint: ''      // e.g. 'https://formspree.io/f/abcdwxyz'
  },

  /* Member portal / login. When set, every "Iniciar sesión" link opens it. */
  memberPortalUrl: '',

  /* Largest single file a member may attach when submitting a notice. */
  maxUploadMb: 10,

  /* Language. Spanish pages live at the site root and English pages under
     /en/ (generated by scripts/build.mjs). The EN/ES toggle switches
     between the two versions of the same page. */
  defaultLanguage: 'es'
};
